stages:
  - containerization
  - deployment

variables:
  DOCKER_IMAGE: 192.168.179.25:5000/ai-result-viewer
  DEPLOYMENT: ai-result-viewer-deployment

containerization:
  stage: containerization
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}

deployment:
  stage: deployment
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${DEPLOYMENT}
  environment:
    name: staging
