apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-result-viewer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-result-viewer-deployment
  template:
    metadata:
      labels:
        app: ai-result-viewer-deployment
    spec:
      containers:
      - name: ai-result-viewer-container
        image: 172.16.98.151:5000/ai-result-viewer
        imagePullPolicy: Always
        ports:
        - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ai-result-viewer-service
  name: ai-result-viewer-service
spec:
  ports:
  - port: 12345
    nodePort: 30114
  selector:
    app: ai-result-viewer-deployment
  type: LoadBalancer
